CREATE USER IF NOT EXISTS 'usuario'@'%' IDENTIFIED BY 'senha_usuario';
GRANT ALL PRIVILEGES ON mydb.* TO 'usuario'@'%';
GRANT CREATE, ALTER, DROP, REFERENCES ON *.* TO 'usuario'@'%';
FLUSH PRIVILEGES;